services:

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ragdb
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: celery -A worker.tasks worker --loglevel=info
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ragdb
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  huggingface_cache: