from worker.ingestion.repo_loader import clone_repo
from worker.ingestion.file_walker import get_files
from backend.database import SessionLocal
from backend.models import Repo, Chunk
from worker.ingestion.chunker import (
    chunk_code_file,
    chunk_markdown_file
)

from worker.embeddings.embedder import generate_embeddings
from retrieval.vector_store import store_chunks
from retrieval.schema import ChunkSchema, ChunkType

import json
import os
import shutil


def ingest_repo(repo_id: int):
    db = SessionLocal()
    repo = None
    try:
        # Find repository row
        repo = db.query(Repo).filter(Repo.id == repo_id).first()

        if not repo:
            raise Exception("Repository not found")

        # Read GitHub URL
        repo_url = repo.github_url

        # Update status
        repo.status = "indexing"
        db.commit()

        # clone repo
        repo_path = clone_repo(repo_url)

        # get all files
        files = get_files(repo_path)

        all_chunks = []
        chunk_objects = []
        chunk_index = 0

        # process files
        for file in files:

            print(f"Processing: {file}")

            if file.endswith((".md", ".rst", ".txt")):

                chunks = chunk_markdown_file(file)

            else:

                chunks = chunk_code_file(file)

            for chunk in chunks:

                all_chunks.append(chunk)

                chunk_obj = Chunk(
                    repo_id=repo.id,
                    chunk_index=chunk_index,
                    file_path=chunk.get("file", ""),
                    chunk_type=chunk.get("type", ""),
                    signature=chunk.get("signature"),
                    start_line=chunk.get("start_line"),
                    end_line=chunk.get("end_line"),
                    content=chunk["content"]
                )

                chunk_objects.append(chunk_obj)

                chunk_index += 1

        print(f"\nTotal chunks: {len(all_chunks)}")

        print("\nSaving chunks to Postgres...")

        db.add_all(chunk_objects)

        db.commit()

        print("Chunks saved")
        repo.total_files = len(files)
        repo.total_chunks = len(all_chunks)

        db.commit()
        # save chunks locally
        os.makedirs("chunks", exist_ok=True)

        with open("chunks/chunks.json", "w") as f:

            json.dump(all_chunks, f, indent=2)

        # generate embeddings
        print("\nGenerating embeddings...")

        embeddings = generate_embeddings(all_chunks)

        # store in chromadb
        print("\nStoring in ChromaDB...")

        schema_chunks = []
        for db_chunk in chunk_objects:
            # Safely parse the chunk type, fallback to PLAINTEXT if it doesn't strictly match the enum
            try:
                c_type = ChunkType(db_chunk.chunk_type)
            except ValueError:
                c_type = ChunkType.PLAINTEXT
                
            schema_chunks.append(ChunkSchema(
                id=str(db_chunk.id),  # This pulls the UUID generated by Postgres
                content=str(db_chunk.content),
                file_path=str(db_chunk.file_path),
                start_line=str(db_chunk.start_line),
                end_line=str(db_chunk.end_line),
                chunk_type=c_type
            ))

        store_chunks(schema_chunks, embeddings, str(repo.id))

        # delete cloned repo
        print("\nDeleting cloned repository...")

        shutil.rmtree(repo_path)

        print("Repository deleted")

        print("\nDone")

        repo.status = "complete"
        db.commit()

    except Exception as e:
        if 'repo' in locals() and repo:
            repo.status = "failed"
            repo.error_message = str(e)
            db.commit()
        raise

    finally:
        db.close()

